### ISSUE TITLE
Link, incorrect language

### ISSUE THREAD

**Issue by tfolbrecht** [githubtraining/oss-enterprise#37]
## Bug Report

**Current behavior**

Link: [The state of enterprise open source: A Red Hat report](https://www.redhat.com/it/enterprise-open-source-report/2019) is in Italian

![image](https://user-images.githubusercontent.com/6099765/73056658-9c193600-3e5d-11ea-9101-6eb3149d8ea8.png)

**Reproduction**
Steps to reproduce the behavior in the course:
1. Go to [https://lab.github.com/githubtraining/paths/become-an-open-source-enterprise](https://lab.github.com/githubtraining/paths/become-an-open-source-enterprise)
2. Click on/ or hover over *The state of enterprise open source: A Red Hat report*
3. The document is in Italian instead of English

**Expected behavior**
The document should be in English

**Possible solution**
use `https://www.redhat.com/en/enterprise-open-source-report/2019` instead

**In addition**
I'm having a hard time finding the Learning Paths markdown and repo, I'll keep trying!

**Comment by brianamarie** [comment]
Thank you for opening this issue, @tfolbrecht! You're right, the Learning Path source material isn't currently in open source repositories. I'll reach out internally to see how we can update this. 😊

**Comment by tfolbrecht** [comment]
Thank you @brianamarie I'll go ahead and close this!
